server:
  port: 8090

spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: authorization-server
          uri: lb://AUTHORIZATION-SERVER
          predicates:
            - Path=/api/login

        - id: huespedes
          uri: lb://HUESPEDES
          predicates:
            - Path=/api/huespedes/**

        - id: habitaciones
          uri: lb://HABITACIONES
          predicates:
            - Path=/api/habitaciones/**

        - id: reservas
          uri: lb://RESERVAS
          predicates:
            - Path=/api/reservas/**

    loadbalancer:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true