spring.application.name=huespedes
server.port=8082

# Oracle
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS:admin}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000